CREATE TABLE MAP_IMAGES_GEOLOCATION (
  UUID varchar(37) NOT NULL,
  POINT POINT NOT NULL COMMENT '经纬度',
  CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (UUID),
  SPATIAL KEY SP_INDEX(POINT)  
) ENGINE=MYISAM DEFAULT CHARSET=UTF8;